apiVersion: 1

deleteDatasources:
  - name: Supabase-43V3RR
    uid: supabase

prune: true

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Supabase-43V3RR
    uid: supabase
    type: postgres
    access: proxy
    url: ${SUPABASE_DB_HOST}:${SUPABASE_DB_PORT}
    database: ${SUPABASE_DB_NAME}
    user: ${SUPABASE_DB_USER}
    secureJsonData:
      password: ${SUPABASE_DB_PASSWORD}
    jsonData:
      database: ${SUPABASE_DB_NAME}
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
